export const GET_TODO_GROUPS_STARTED = 'GET_TODO_GROUPS_STARTED';
export const GET_TODO_GROUPS_SUCCESS = 'GET_TODO_GROUPS_SUCCESS';
export const GET_TODO_GROUPS_FAILURE = 'GET_TODO_GROUPS_FAILURE';

export const ADD_NEW_TODO_GROUP_STARTED = 'ADD_NEW_TODO_GROUP_STARTED';
export const ADD_NEW_TODO_GROUP_SUCCESS = 'ADD_NEW_TODO_GROUP_SUCCESS';
export const ADD_NEW_TODO_GROUP_FAILURE = 'ADD_NEW_TODO_GROUP_FAILURE';

export const DELETE_TODO_GROUP_STARTED = 'DELETE_TODO_GROUP_STARTED';
export const DELETE_TODO_GROUP_SUCCESS = 'DELETE_TODO_GROUP_SUCCESS';
export const DELETE_TODO_GROUP_FAILURE = 'DELETE_TODO_GROUP_FAILURE';

export const GET_ALL_TODOS_STARTED = 'GET_ALL_TODOS_STARTED';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';
export const GET_ALL_TODOS_FAILURE = 'GET_ALL_TODOS_FAILURE';

export const ADD_NEW_TODO_STARTED = 'ADD_NEW_TODO_STARTED';
export const ADD_NEW_TODO_SUCCESS = 'ADD_NEW_TODO_SUCCESS';
export const ADD_NEW_TODO_FAILURE = 'ADD_NEW_TODO_FAILURE';

export const TOGGLE_CHECK_STARTED = 'TOGGLE_CHECK_STARTED';
export const TOGGLE_CHECK_SUCCESS = 'TOGGLE_CHECK_SUCCESS';
export const TOGGLE_CHECK_FAILURE = 'TOGGLE_CHECK_FAILURE';

export const DELETE_TODO_STARTED = 'DELETE_TODO_STARTED';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const EDIT_TODO_STARTED = 'EDIT_TODO_STARTED';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE';

export const HOST_NAME = 'http://localhost:8080';