export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const EDIT_START = 'EDIT_START';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_ERROR = 'EDIT_ERROR';

export const MARK_DONE_START = 'MARK_DONE_START';
export const MARK_DONE_SUCCESS = 'MARK_DONE_SUCCESS';
export const MARK_DONE_ERROR = 'MARK_DONE_ERROR';
