export const ADD_PRODUCT_QUANTITY = 'ADD_PRODUCT_QUANTITY';
export const REMOVE_PRODUCT_QUANTITY = 'REMOVE_PRODUCT_QUANTITY';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
